#!/bin/sh

echo "                                                                     "
echo "                          ...                                        "
echo "                       .:kKXXOo.                          ..         "
echo "         ;d;          .kWMWWWMMK;                         ,xo.       "
echo "       .oOl.         .xXkc;;:xXMK;                         ,kO;      "
echo "      'k0:           ;Oc      ;0Wk.                         .kKc     "
echo "     'OK;            :l.       ;KNl                          .kXl.   "
echo "    'OXc                        lNO.                          ,KXc   "
echo "   .xWx.                        .ONl.                          oNK;  "
echo "   cNX:                         .dWOc.                         ,0Wx. "
echo "  .OMO.                         ,0MNKc                         .xMX: "
echo "  :XMx.                        'OMMMWk.                         oWWd "
echo "  oWWd                        'OWMMMMX:                         lNMk."
echo " .xMWo                       .kWMMWNNWx.                        cNMO."
echo " .xMWo                      .xWMMWxlxKK;                        cNMO."
echo " .dWWo                     .xWMMWx..,xWd.                       lWMx."
echo "  cNMx.                   .dNMMWO.   :X0,                       dWNl "
echo "  '0MO.                  .oNMMM0'    .kNo                      .kM0, "
echo "   oNX:                  lNMMMK;      cN0'                     ;KNo  "
echo "   .kWx.                lXMMMK:       .OWd.       ..          .dWk.  "
echo "    ,0Xc               cXMMMXc         lNXc       cd.         cX0,   "
echo "     ;00;             :KMMMNl          .OMXd'   .:0d.        ;00,    "
echo "      ,O0:           ;KMMMNd.           ;KMWXOxx0NK;        :0k'     "
echo "      .d0l.         ;0MMMWx.             ;ONMMMMWO;       .oOl.      "
echo "        ;d:         ':ccc;.               .'cool;.        ,l,        "
echo "                                                                     "

