#!/usr/bin/python
# coding=UTF-8
# These glyphs, and the mapping of file extensions to glyphs
# has been copied from the vimscript code that is present in
# https://github.com/ryanoasis/vim-devicons
import re;
import os;

# all those glyphs will show as weird squares if you don't have the correct patched font
# My advice is to use NerdFonts which can be found here:
# https://github.com/ryanoasis/nerd-fonts
file_node_extensions = {
    '7z'       : '',
    'asd'      : '',
    'avi'      : '',
    'bat'      : '',
    'bmp'      : '',
    'bz2'      : '',
    'c'        : '',
    'c++'      : '',
    'cab'      : '',
    'cc'       : '',
    'conf'     : '',
    'cp'       : '',
    'cpio'     : '',
    'cpp'      : '',
    'cxx'      : '',
    'db'       : '',
    'deb'      : '',
    'diff'     : '',
    'dump'     : '',
    'epub'     : '',
    'exe'      : '',
    'fasl'     : '',
    'flac'     : '',
    'flv'      : '',
    'gif'      : '',
    'gz'       : '',
    'gzip'     : '',
    'hs'       : '',
    'htm'      : '',
    'html'     : '',
    'ico'      : '',
    'ini'      : '',
    'java'     : '',
    'jpeg'     : '',
    'jpg'      : '',
    'js'       : '',
    'json'     : '',
    'lha'      : '',
    'lhs'      : '',
    'lisp'     : '',
    'log'      : '',
    'lsp'      : '',
    'lua'      : '',
    'lzh'      : '',
    'lzma'     : '',
    'markdown' : '',
    'md'       : '',
    'mkv'      : '',
    'mov'      : '',
    'mp3'      : '',
    'mp4'      : '',
    'mpeg'     : '',
    'mpg'      : '',
    'ogg'      : '',
    'pdf'      : '',
    'pl'       : '',
    'pm'       : '',
    'png'      : '',
    'py'       : '',
    'pyc'      : '',
    'pyd'      : '',
    'pyo'      : '',
    'rar'      : '',
    'rc'       : '',
    'rpm'      : '',
    'rss'      : '',
    'service'  : '',
    'sexp'     : '',
    'sh'       : '',
    'sln'      : '',
    'sql'      : '',
    'suo'      : '',
    'tar'      : '',
    'tgz'      : '',
    'timer'    : '',
    'vim'      : '',
    'vimrc'    : '',
    'wav'      : '',
    'wallpaper': '',
    'webm'     : '',
    'xml'      : '',
    'xul'      : '',
    'xz'       : '',
    'yml'      : '',
    'zip'      : '',
}

dir_node_exact_matches = {
    '.git'                             : '',
    '.gnupg'                           : '',
    '.ssh'                             : '',
    'Dropbox'                          : '',
}

file_node_exact_matches = {
    '.Xresources'                      : '',
    '.aliases'                         : '',
    '.bash_logout'                     : '',
    '.bash_profile'                    : '',
    '.bash_prompt'                     : '',
    '.bashrc'                          : '',
    '.conkyrc'                         : '',
    '.gitconfig'                       : '',
    '.gitignore'                       : '',
    '.gitignore_global'                : '',
    '.inputrc'                         : '',
    '.motd_pic'                        : '',
    '.screenrc'                        : '',
    '.screenrc_nointerface'            : '',
    '.xaliases'                        : '',
    '.xprofile'                        : '',
    '.xinitrc'                         : '',
    '.xserverrc'                       : '',
    'config'                           : '',
    'preferences'                      : '',
    'vimrc'                            : '',
}

def devicon(file):
  if file.is_directory: return dir_node_exact_matches.get(file.relative_path, '')
  return file_node_exact_matches.get(file.relative_path, file_node_extensions.get(file.extension, ''))

